INSERT INTO Lists
	(ListNameID, ListName, ListValueID, ListValue, DateCreated)
VALUES
(1,'TreatmentFacility',2,'Healing House', CURRENT_TIMESTAMP),
(2,'EducationLevel',3,'8th grade and below', CURRENT_TIMESTAMP),
(2,'EducationLevel',4,'Above 8th grade below High School', CURRENT_TIMESTAMP),
(2,'EducationLevel',5,'High School Diploma', CURRENT_TIMESTAMP),
(2,'EducationLevel',6,'College Credit, No Diploma', CURRENT_TIMESTAMP),
(2,'EducationLevel',7,'Trade/Technical/Vocation Training', CURRENT_TIMESTAMP),
(2,'EducationLevel',8,'Associates Degree', CURRENT_TIMESTAMP),
(2,'EducationLevel',9,'Bachelors Degree', CURRENT_TIMESTAMP),
(2,'EducationLevel',10,'Masters Degree', CURRENT_TIMESTAMP),
(2,'EducationLevel',11,'PhD', CURRENT_TIMESTAMP),
(3,'Sessions',12,'Overnight Stay', CURRENT_TIMESTAMP),
(3,'Sessions',13,'Class', CURRENT_TIMESTAMP),
(3,'Sessions',14,'Counseling', CURRENT_TIMESTAMP),
(3,'Sessions',15,'Skill Training', CURRENT_TIMESTAMP),
(3,'Sessions',16,'Chapel', CURRENT_TIMESTAMP),
(3,'Sessions',17,'Devotion', CURRENT_TIMESTAMP),
(3,'Sessions',18,'Guest', CURRENT_TIMESTAMP),
(3,'Sessions',19,'Assessment', CURRENT_TIMESTAMP),
(3,'Sessions',20,'Healing', CURRENT_TIMESTAMP),
(3,'Sessions',21,'Transition', CURRENT_TIMESTAMP),
(3,'Sessions',22,'After-care', CURRENT_TIMESTAMP),
(3,'Sessions',23,'Graduated', CURRENT_TIMESTAMP),
(3,'Sessions',24,'Moved out', CURRENT_TIMESTAMP),
(3,'Sessions',25,'FullRestriction', CURRENT_TIMESTAMP),
(3,'Sessions',26,'Partial Restriction', CURRENT_TIMESTAMP),
(4,'NoteCategory',27,'Admission', CURRENT_TIMESTAMP),
(4,'NoteCategory',28,'Medical', CURRENT_TIMESTAMP),
(4,'NoteCategory',29,'Medication', CURRENT_TIMESTAMP),
(4,'NoteCategory',30,'Billing', CURRENT_TIMESTAMP),
(4,'NoteCategory',31,'Employment', CURRENT_TIMESTAMP),
(4,'NoteCategory',32,'Education', CURRENT_TIMESTAMP),
(4,'NoteCategory',33,'Financial', CURRENT_TIMESTAMP),
(4,'NoteCategory',34,'Contact', CURRENT_TIMESTAMP),
(4,'NoteCategory',35,'Discipline', CURRENT_TIMESTAMP),
(4,'NoteCategory',36,'Graduation', CURRENT_TIMESTAMP),
(4,'NoteCategory',37,'After-Care', CURRENT_TIMESTAMP),
(4,'NoteCategory',38,'Exit', CURRENT_TIMESTAMP),
(4,'NoteCategory',39,'Legal', CURRENT_TIMESTAMP),
(4,'NoteCategory',40,'Spiritual', CURRENT_TIMESTAMP),
(5,'MaritalStatus',41,'Single', CURRENT_TIMESTAMP),
(5,'MaritalStatus',42,'Engaged', CURRENT_TIMESTAMP),
(5,'MaritalStatus',43,'Married', CURRENT_TIMESTAMP),
(5,'MaritalStatus',44,'Seperated', CURRENT_TIMESTAMP),
(5,'MaritalStatus',45,'Divorced', CURRENT_TIMESTAMP),
(5,'MaritalStatus',46,'Widowed', CURRENT_TIMESTAMP),
(6,'DebtType',47,'Fines', CURRENT_TIMESTAMP),
(6,'DebtType',48,'ChildSupportBackPay', CURRENT_TIMESTAMP),
(6,'DebtType',49,'LicenseFees', CURRENT_TIMESTAMP),
(6,'DebtType',50,'Loans', CURRENT_TIMESTAMP),
(6,'DebtType',51,'CreditCard', CURRENT_TIMESTAMP),
(6,'DebtType',52,'Mortgages', CURRENT_TIMESTAMP),
(7,'RaceType',53,'American Indian or Alaska Native', CURRENT_TIMESTAMP),
(7,'RaceType',54,'Asian', CURRENT_TIMESTAMP),
(7,'RaceType',55,'Black or African American', CURRENT_TIMESTAMP),
(7,'RaceType',56,'Hispanic or Latino', CURRENT_TIMESTAMP),
(7,'RaceType',57,'Native Hawaiian or Other Pacific Islander', CURRENT_TIMESTAMP),
(7,'RaceType',58,'White', CURRENT_TIMESTAMP);
